steps:
  - label: "GNN CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GraphNeuralNetworks"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - GraphNeuralNetworks/src
            - GraphNeuralNetworks/ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GNN_TEST_CUDA: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60

  - label: "GNN AMDGPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GraphNeuralNetworks"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - GraphNeuralNetworks/src
            - GraphNeuralNetworks/ext
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    env:
      GNN_TEST_AMDGPU: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60

  - label: "GNNlib CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GNNlib"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - GNNlib/src
            - GNNlib/ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GNN_TEST_CUDA: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60

  - label: "GNNlib AMDGPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GNNlib"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - GNNlib/src
            - GNNlib/ext
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    env:
      GNN_TEST_AMDGPU: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60

  - label: "GNNGraphs CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GNNGraphs"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - GNNGraphs/src
            - GNNGraphs/ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GNN_TEST_CUDA: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60

  - label: "GNNGraphs AMDGPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
            project: "GNNGraphs"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - GNNGraphs/src
            - GNNGraphs/ext
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    env:
      GNN_TEST_AMDGPU: "true"
      GNN_TEST_CPU: "false"
    timeout_in_minutes: 60
