name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - name: Tag GraphNeuralNetworks
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          subdir: GraphNeuralNetworks
      - name: Tag GNNlib
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          subdir: GNNlib
      - name: Tag GNNGraphs
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          subdir: GNNGraphs
          changelog: |
            ## {{ package }} {{ version }}

            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}

            {% if custom %}
            {{ custom }}
            {% endif %}

            {% if backport %}
            This release has been identified as a backport.
            Automated changelogs for backports tend to be wildly incorrect.
            Therefore, the list of issues and pull requests is hidden.
            <!--
            {% endif %}
            {% if pulls %}
            **Merged pull requests:**
            {% for pull in pulls %}
            {% if "gnngraphs" in pull.labels %}
            - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
            {% endif %}
            {% endfor %}
            {% endif %}

            {% if issues %}
            **Closed issues:**
            {% for issue in issues %}
            {% if "gnngraphs" in issue.labels %}
            - {{ issue.title }} (#{{ issue.number }})
            {% endif %}
            {% endfor %}
            {% endif %}

            {% if backport %}
            -->
            {% endif %}
      - name: Tag GNNLux
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          subdir: GNNLux
